### ISSUE TITLE
error: ‘protobuf_AddDesc_caffe_2eproto’ is not a member of ‘caffe’ 

### ISSUE THREAD

**Issue by lpplbiubiubiub** [WIStudent/DeepMatchingGPU#1]
i followed your install, but when i make DeepMatchingGPU, there are some errors:
`gpudm_wrap.cxx: In function ‘PyObject* _wrap_protobuf_AddDesc_caffe_2eproto(PyObject*, PyObject*)’:
gpudm_wrap.cxx:15379:3: error: ‘protobuf_AddDesc_caffe_2eproto’ is not a member of ‘caffe’
   caffe::protobuf_AddDesc_caffe_2eproto();
   ^
gpudm_wrap.cxx: In function ‘PyObject* _wrap_protobuf_AssignDesc_caffe_2eproto(PyObject*, PyObject*)’:
gpudm_wrap.cxx:15391:3: error: ‘protobuf_AssignDesc_caffe_2eproto’ is not a member of ‘caffe’
   caffe::protobuf_AssignDesc_caffe_2eproto();
   ^
gpudm_wrap.cxx: In function ‘PyObject* _wrap_protobuf_ShutdownFile_caffe_2eproto(PyObject*, PyObject*)’:
gpudm_wrap.cxx:15403:3: error: ‘protobuf_ShutdownFile_caffe_2eproto’ is not a member of ‘caffe’
   caffe::protobuf_ShutdownFile_caffe_2eproto();
   ^
make: *** [gpudm_wrap.o] Error 1
`
i think i have a different vesion of protobuf, so could you tell me your version of protobuf?

**Comment by WIStudent** [comment]
I think i installed version 3.0.0, but your issue might be a different one. The original developers used swig to generate glue code between C++ and Python. Like them I included the generated glue code in the repository, but because of recent changes in Caffe it might be necessary to generate that glue code again. Try the following:
```
make clean
make cleanswig
make all
```
Your first `make all` will now probably fail, like the original authors described:
```
   (IMPORTANT NOTE: 
    if you compile the SWIG file, it is normal that you see lots of errors. 
    However, as long as it generates 'gpudm_warp.cxx', you can just relaunch 
'make' and the rest of the compilation should go smoothly. )
```

**Comment by lpplbiubiubiub** [comment]
It worked， thank you！
